### PR TITLE
Issue#1057 adding snippets for CreateTableFromSnapshot

### PR DESCRIPTION
**Pull request by roopak-qlogic**
Fixes issue #1057

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/google-cloud-cpp/1174)

### CODE REVIEW

**Comment by roopak-qlogic** [comment]
I thought snapshot related examples, can not run on emulator ( like earlier example for get, list and delete snapshot), let me try to add in ci build.

**Comment by roopak-qlogic** [comment]
here it require cluster-id and snapshot-id  to run this examples, and it will be applicable for all snapshots examples ( which is currently not added in ci build), will try to figure out the approach.

**Comment by roopak-qlogic** [comment]
I tried to include this example in ci build, but  following are the observation 
1. Seems all snapshots examples does not support by emulator.
2. examples require Cluster-id and snapshot-id in addition of other parameters, not figure out how to pass
Please suggest, if anything i am missing here.

**Comment by coryan** [comment]
Ack, thanks for looking into it.

**Pull request merged**
